name: Build dacpac

on:
  push:
    branches: [ live ]
  workflow_dispatch:

jobs:
  publish-job:
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build dacpac
        run: msbuild ".\source\ntbs-reporting.sqlproj"

      - name: Copy dacpac to build directory
        run: Copy-Item ".\source\bin\Output\ntbs-reporting.dacpac" ".\build"

      - name: Push to branch
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "github-actions"
          git commit -am "Build dacpac"
          git push