name: Build dacpac

on:
  push:
    branches: [ live ]
  workflow_dispatch:

jobs:
  build-dacpac:
    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build dacpac
        run: msbuild ".\source\ntbs-reporting.sqlproj"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: reporting-dacpac
          path: source/bin/Output/ntbs-reporting.dacpac
          if-no-files-found: error
          retention-days: 5

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: build-dacpac

    steps:
      - name: Set image tag name
        id: set_tag_name
        run: echo '::set-output name=TAG_NAME::${{ format('build-{0}', github.sha) }}'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: reporting-dacpac
          path: "./source/bin/Output"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/publichealthengland/ntbs-reporting:${{ steps.set_tag_name.outputs.TAG_NAME }}
